public class sampleCon {

 String [] countries = new String []{};
 public PageReference Test()
 {
     return Null;
 }
 Public List<SelectOption> getitems()
 {
         List<SelectOption> options = new List<SelectOption>();
         options.add(new SelectOption('US', 'India') );
         return options;
 }
 Public String[]getCountries()
 {
         return Countries; 
 }
 public void setCountries(String[] countries)
 {
         this.countries=countries;
 }
}